### ISSUE TITLE
Converting HTML to Markdown strips anchor tag pairs without content on Ubuntu.

### ISSUE THREAD

**Issue by jdickey** [alphabetum/pandoc-ruby#18]
Consider the specs in [this short vendor-verification spec file](https://github.com/TheProlog/prolog-services-replace_content/blob/054006a/test/vendor_verification/pandoc_basics_test.rb). The tests pass when run on Mac OS X 10.11.4 with Pandoc 1.17.0.3 installed and using `pandoc-ruby` 2.0.0 as bundled.

Run in an Ubuntu CI system (CodeShip) with Pandoc 1.17.0.3 and `pandoc-ruby` 2.0.0, and the tests die. Specifically, when the HTML

``` html
<p>This is <a id="contribution-27-begin"></a><a id="contribution-9-begin"></a>obviously <em>sample <a id="contribution-27-end"></a> and disposable</em> content.<a id="contribution-9-end"></a></p>
```

is converted to Markdown via `PandocRuby.convert(html_content, from: :html, to: :markdown_github)`, the resulting Markdown is `This is obviously *sample and disposable* content.\n`. The tag pairs such as `<a id="contribution-27-begin"></a>` are simply removed completely.

Again, this happens in the Ubuntu build, but does not happen under OS X, where the converted Markdown appears as `This is <a href="" id="contribution-27-begin"></a><a href="" id="contribution-9-begin"></a>obviously *sample <a href="" id="contribution-27-end"></a> and disposable* content.<a href="" id="contribution-9-end"></a>\n`, which is as expected.

What gives with the Ubuntu?

**Comment by alphabetum** [comment]
This has presumably been addressed separately, but for what it's worth, I wasn't able to reproduce the issue on Ubuntu 18.10 with Pandoc 2.2.1 using the HTML content from the linked spec. As seen below, the output currently appears to contain the additional tags:

```ruby
pry(main)> markdown = PandocRuby.convert(html_content, from: :html, to: :markdown_github)
=> "This is <span id=\"contribution-27-begin\"></span> <span\nid=\"contribution-9-begin\"></span> obviously *sample <span\nid=\"contribution-27-end\"></span> and disposable* content. <span\nid=\"contribution-9-end\"></span>\n"

pry(main)> PandocRuby.convert(markdown, from: :markdown_github, to: :html).chomp
=> "<p>This is <span id=\"contribution-27-begin\"></span> <span\nid=\"contribution-9-begin\"></span> obviously <em>sample <span\nid=\"contribution-27-end\"></span> and disposable</em> content. <span\nid=\"contribution-9-end\"></span></p>"
```

I'm not sure what was causing the issue since PandocRuby just uses the pandoc output and doesn't really manipulate it. 😕

**Comment by jdickey** [comment]
Thanks for following up! We'd abandoned pandoc(-ruby) for that project, which fell by the wayside for entirely unrelated reasons later. I'll be working on a similar project in a few months, and I'll give pandoc-ruby and GFM <=> HTML conversion another go.
