### ISSUE TITLE
Pandoc deprecated --chapter in favor of --top-level-division=chapter

### ISSUE THREAD

**Issue by Merovex** [alphabetum/pandoc-ruby#30]
Receiving an error just recently where --chapter has been deprecated by Pandoc in favor of --top-level-division=chapter. Changed in 2016 (http://pandoc.org/releases.html#pandoc-1.18-26-oct-2016)

(I had an old version of Pandoc)

```
RuntimeError: --chapters has been removed. Use --top-level-division=chapter instead.
Try pandoc --help for more information.
/Users/.../pandoc-ruby-2.0.2/lib/pandoc-ruby.rb:222:in `execute'
/Users/.../pandoc-ruby-2.0.2/lib/pandoc-ruby.rb:198:in `execute_pandoc'
/Users/.../pandoc-ruby-2.0.2/lib/pandoc-ruby.rb:190:in `convert_string'
/Users/.../pandoc-ruby-2.0.2/lib/pandoc-ruby.rb:132:in `convert'
/Users/.../pandoc-ruby-2.0.2/lib/pandoc-ruby.rb:166:in `block (2 levels) in <class:PandocRuby>'
```

**Comment by alphabetum** [comment]
It looks like this was due the 'chapters' option being specified when calling PandocRuby, e.g., `PandocRuby.convert('Example', :chapters)`. I realize this is an outdated issue, but just so it's recorded here in case someone finds it useful, this can be resolved by replacing the `:chapters` argument with the new option, as in `PandocRuby.convert('Example', 'top-level-division' => 'chapter')`.
